name: PR Check
on:
  pull_request:
  workflow_dispatch:
jobs:
  pr_check:
    permissions:
      contents: write
      pull-requests: write
    uses: LikeTheSalad/github-tools/.github/workflows/pr-check.yml@main
    with:
      app-id: '${{ vars.APP_ID }}'
      java-version: '17'
      checks-command: './check.sh'
      run-on-windows: true
    secrets:
      GH_BOT_PRIVATE_KEY: '${{ secrets.GH_BOT_PRIVATE_KEY }}'

  checks:
    name: checks
    if: ${{ always() }}
    needs: pr_check
    runs-on: ubuntu-latest
    steps:
      - name: Finalize check status
        env:
          RESULT: ${{ needs.pr_check.result }}
        run: |
          test "$RESULT" = "success"
