name: Release — Publish
on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'
jobs:
  release:
    uses: LikeTheSalad/github-tools/.github/workflows/release-publish.yml@main
    with:
      java-version: 17
      app-id: '${{ vars.APP_ID }}'
      publish-to-gradle-portal: true
    secrets: inherit
